version: '3'

services:
  upgrader:
    container_name: upgrader
    restart: on-failure
    depends_on:
      - tcp_server
    env_file:
      - modbus_upgrader/.env.local
    ports:
      - '5020:5020'
      - '502'
    build:
      dockerfile: Dockerfile
      context: modbus_upgrader
  tcp_server:
    container_name: tcp_server
    restart: on-failure
    env_file:
      - tcp_server/.env.local
    ports:
      - '502:502'
    build:
      dockerfile: Dockerfile
      context: tcp_server
  tls_client:
    container_name: tls_client
    restart: on-failure
    depends_on:
      - upgrader
      - tcp_server
    env_file:
      - tls_client/.env.local
    ports:
      - '502'
    build:
      dockerfile: Dockerfile
      context: tls_client
