version: '3'

services:
  upgrader:
    container_name: upgrader
    restart: on-failure
    env_file:
      - modbus_upgrader/.env.local
    ports:
      - '5020:5020'
      - '502'
    build:
      dockerfile: Dockerfile
      context: modbus_upgrader
  server:
    container_name: server
    restart: on-failure
    env_file:
      - server/.env.local
    ports:
      - '502:502'
    build:
      dockerfile: Dockerfile
      context: server
  client:
    container_name: client
    restart: on-failure
    env_file:
      - tcp_client/.env.local
    ports:
      - '502'
    build:
      dockerfile: Dockerfile
      context: tcp_client
