version: '3'

services:
  upgrader:
    container_name: upgrader
    restart: on-failure
    build:
      dockerfile: Dockerfile
      context: modbus_upgrader
  server:
    container_name: server
    restart: on-failure
    build:
      dockerfile: Dockerfile
      context: server
  client:
    container_name: client
    restart: on-failure
    build:
      dockerfile: Dockerfile
      context: tcp_client
